# Generated by Django 2.1.5 on 2019-01-11 04:30

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.AddField(
            model_name='like',
            name='unique_identifier',
            field=models.CharField(default=backend.utils.id_generator, max_length=8, primary_key=True, serialize=False),
        ),
    ]
