# Generated by Django 2.1.4 on 2019-01-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='threads',
            field=models.ManyToManyField(blank=True, to='backend.Thread'),
        ),
    ]
