# Generated by Django 2.1.5 on 2019-01-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
