# Generated by Django 2.1.5 on 2019-01-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190110_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_created', 'date_updated', 'title']},
        ),
    ]
