# Generated by Django 2.1.5 on 2019-01-10 14:08

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190110_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_identifier',
            field=models.CharField(default=backend.utils.id_generator, max_length=8, primary_key=True, serialize=False),
        ),
    ]
