# Generated by Django 2.1.5 on 2019-01-08 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20190108_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='id',
        ),
        migrations.AddField(
            model_name='thread',
            name='unique_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, primary_key=True, serialize=False),
        ),
    ]
