# Generated by Django 2.1.5 on 2019-01-08 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20190108_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
