# Generated by Django 2.1.5 on 2019-01-08 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_auto_20190108_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
