# Generated by Django 2.1.5 on 2019-01-08 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_auto_20190108_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
    ]
