# Generated by Django 2.1.5 on 2019-01-08 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_auto_20190108_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
