# Generated by Django 2.1.5 on 2019-01-09 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0014_auto_20190108_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='admins',
            field=models.ManyToManyField(related_name='OwnedThreads', to=settings.AUTH_USER_MODEL),
        ),
    ]
