# Generated by Django 2.1.5 on 2019-01-09 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0015_thread_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('nickname', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='admins',
        ),
        migrations.AddField(
            model_name='threadmember',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='threads.Thread'),
        ),
        migrations.AddField(
            model_name='threadmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='members',
            field=models.ManyToManyField(through='threads.ThreadMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
