# Generated by Django 2.1.5 on 2019-01-09 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0016_auto_20190109_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='members',
            field=models.ManyToManyField(related_name='joined_threads', through='threads.ThreadMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
