# Generated by Django 2.1.5 on 2019-01-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0017_auto_20190109_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='members',
        ),
    ]
