# Generated by Django 2.1.5 on 2019-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0019_auto_20190110_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_image',
            field=models.ImageField(default='default_thread.jpeg', upload_to='profile_pics'),
        ),
    ]
