# Generated by Django 2.1.5 on 2019-01-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0020_thread_thread_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_banner',
            field=models.ImageField(default='default_thread_banner.jpeg', upload_to='threads/banner'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_image',
            field=models.ImageField(default='default_thread.jpeg', upload_to='threads/profile'),
        ),
    ]
