# Generated by Django 2.1.5 on 2019-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
